[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Add your Sanity project details
  PUBLIC_SANITY_PROJECT_ID = "j4vtw3ym"
  PUBLIC_SANITY_DATASET = "production-dataset"

  # Optional: API version
  PUBLIC_SANITY_API_VERSION = "2024-01-01"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# If you're using Astro's image optimization
[[headers]]
  for = "/_image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"